### ISSUE TITLE
improve complex formula expansions

### ISSUE THREAD

**Issue by bbolker** [cran/reformulas#1]
It would be good if `expandAllGrpVar(quote((1 | a / (b*c))))` returned `(1|a) + (1 | a:b) + (1 | a:c) + (1 | a:b:c)`. (It doesn't at present.)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by bbolker** [comment]
d'oh!  Thought I was posting to my own repo (I hope that response was automatic ...)
